[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/=lib/chainlink-brownie-contracts/contracts/",
    "chainlink-brownie-contracts/=/home/redteamer/foundry-f23/foundry-fund-me-f24/lib/chainlink-brownie-contracts/",
    "forge-std/=/home/redteamer/foundry-f23/foundry-fund-me-f24/lib/forge-std/src/",
]

ffi = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
